const COMMANDS = Object.freeze({
  MUNIN: "!munin",
  PING: "!ping",
  ECHO: "!echo",
  CREATE_CUSTOM_COMMAND: "!comando",
  LIST_CUSTOM_COMMANDS: "!comandos",
  SAVE_MESSAGE: "!guardar",
  VIEW_SAVED_MESSAGE: "!ver",
  LIST_SAVED_MESSAGES: "!guardados",
  DELETE_SAVED_MESSAGE: "!borrar",
  PENDING: "!p",
  REMINDER: "!r",
  COIN: "!moneda",
  DICE: "!dado",
  EIGHT_BALL: "!bola8",
  RANDOM: "!elige",
  POLL: "!encuesta",
  MULTIPLE_POLL: "!encuestam",
  TIMER: "!tiempo",
  SUMMARY: "!resumen",
  BAN: "!ban",
  CONFIG: "!config",
  UNBAN: "!unban",
  ADMIN: "!admin",
  NO_ADMIN: "!noadmin",
  PAUSE: "!pausa",
  UNPAUSE: "!despausa",
  CURRENT_CLASS: "!clase",
  LIST_CLASSES_TODAY: "!clases",
  LIST_ALL_CLASSES: "!todaslasclases",
  ADD_CLASS: "!agregarclase",
  EDIT_CLASS: "!editarclase",
  DELETE_CLASS: "!eliminarclase",
  BELL: "!campana",
  HELP: "!ayuda",
  STATS: "!stats",
  REPORT: "!reporte",
  USE_REPORT: "!usarreporte",
  CAT: "!gato",
  DOG: "!perro",
  WEATHER: "!clima",
  TRIVIA: "!trivia",
});

const INFINITE_TOKEN = "inf";

module.exports = { COMMANDS, INFINITE_TOKEN };
