const COMMANDS = Object.freeze({
  MUNIN: "!munin",
  PING: "!ping",
  ECHO: "!echo",
  CREATE_CUSTOM_COMMAND: "!comando",
  SAVE_MESSAGE: "!guardar",
  VIEW_SAVED_MESSAGE: "!ver",
  LIST_SAVED_MESSAGES: "!guardados",
  PENDING: "!p",
  REMINDER: "!r",
  COIN: "!moneda",
  DICE: "!dado",
  EIGHT_BALL: "!bola8",
  RANDOM: "!elige",
  POLL: "!encuesta",
  MULTIPLE_POLL: "!encuestam",
  TIMER: "!tiempo",
  BAN: "!ban",
  BANS: "!bans",
  UNBAN: "!unban",
  ADMIN: "!admin",
  NO_ADMIN: "!noadmin",
  PAUSE: "!pausa",
  UNPAUSE: "!despausa",
  CURRENT_CLASS: "!clase",
  LIST_CLASSES_TODAY: "!clases",
  LIST_ALL_CLASSES: "!todaslasclases",
  ADD_CLASS: "!agregarclase",
  EDIT_CLASS: "!editarclase",
  DELETE_CLASS: "!eliminarclase",
  BELL: "!campana",
  HELP: "!ayuda",
});

const COIN_SIDES = Object.freeze(["cara", "cruz"]);
const INFINITE_TOKEN = "x";
const EIGHT_BALL_RESPONSES = Object.freeze([
  "Sí",
  "No",
  "Tal vez",
  "Definitivamente",
  "Pregunta de nuevo más tarde",
  "No cuentes con ello",
  "Es cierto",
  "No es cierto",
  "No puedo predecirlo ahora",
  "Las perspectivas son buenas",
  "Las perspectivas no son buenas",
  "Sin duda",
  "No lo creo",
  "Sí, definitivamente",
  "Mis fuentes dicen que no",
  "No puedo decirlo ahora",
  "Concéntrate y pregunta de nuevo",
  "Mi respuesta es no",
  "Mi respuesta es sí",
  "Puedes confiar en ello",
]);

const HELP_PAGE_COUNT = 5;
const HELP_PAGES = Object.freeze([
  [
    `=== Ayuda 1/${HELP_PAGE_COUNT} ===`,
    "Secciones:",
    "1. General",
    "2. Pendientes y recordatorios",
    "3. Diversión",
    "4. Clases",
    "5. Admin",
    "",
    "=== General ===",
    `${COMMANDS.MUNIN} - Saludar al bot`,
    `${COMMANDS.PING} - Probar el bot`,
    `${COMMANDS.ECHO} <texto> - Repetir texto`,
    `${COMMANDS.CREATE_CUSTOM_COMMAND} !<nombre> <respuesta> - Crear o sobreescribir un comando personalizado`,
    `${COMMANDS.SAVE_MESSAGE} <título> - Guardar un mensaje respondido`,
    `${COMMANDS.VIEW_SAVED_MESSAGE} <título> - Ver un mensaje guardado`,
    `${COMMANDS.LIST_SAVED_MESSAGES} - Mostrar títulos guardados`,
    `${COMMANDS.HELP} <página> - Ver una página de ayuda`,
  ].join("\n"),
  [
    `=== Ayuda 2/${HELP_PAGE_COUNT}: Pendientes y recordatorios ===`,
    `${COMMANDS.PENDING} [@<dd/mm>] <pendiente> - Guardar un pendiente; sin argumentos, mostrarlos; ${COMMANDS.PENDING} - <índice>, eliminarlo`,
    `${COMMANDS.REMINDER} <cantidad><m/h/d> [x<veces> o x] <contenido> - Crear un recordatorio; sin argumentos, mostrarlos; ${COMMANDS.REMINDER} - <índice>, eliminarlo`,
  ].join("\n"),
  [
    `=== Ayuda 3/${HELP_PAGE_COUNT}: Diversión ===`,
    `${COMMANDS.COIN} - Lanzar una moneda`,
    `${COMMANDS.DICE} - Lanzar un dado`,
    `${COMMANDS.EIGHT_BALL} - Preguntar a la bola 8`,
    `${COMMANDS.RANDOM} <opción1>, <opción2> ... , <opciónN> - Elegir una opción al azar`,
    `${COMMANDS.POLL} <título>,<opción1>,<opción2>,...,<opciónN> - Crear una encuesta`,
    `${COMMANDS.MULTIPLE_POLL} <título>,<opción1>,<opción2>,...,<opciónN> - Crear una encuesta de selección múltiple`,
    `${COMMANDS.TIMER} <cantidad><s/m/h> - Iniciar un temporizador`,
  ].join("\n"),
  [
    `=== Ayuda 4/${HELP_PAGE_COUNT}: Clases ===`,
    `${COMMANDS.CURRENT_CLASS} - Mostrar la clase actual o la siguiente`,
    `${COMMANDS.LIST_CLASSES_TODAY} - Mostrar las clases de hoy`,
    `${COMMANDS.LIST_ALL_CLASSES} - Mostrar todas las clases`,
    `${COMMANDS.ADD_CLASS} <nombre>, <día>, <inicio>-<fin>, <salón> - Agregar una clase`,
    `${COMMANDS.EDIT_CLASS} <nombre o índice>, <campo>=<valor> - Editar una clase`,
    `${COMMANDS.DELETE_CLASS} <nombre o índice> - Eliminar una clase`,
    `${COMMANDS.BELL} - Activar/desactivar recordatorios de 10 minutos antes de clase`,
  ].join("\n"),
  [
    `=== Ayuda 5/${HELP_PAGE_COUNT}: Admin ===`,
    `${COMMANDS.BAN} @usuario <cantidad><m/h/d> o ${INFINITE_TOKEN} - Bloquear comandos de un usuario`,
    `${COMMANDS.BANS} - Mostrar usuarios bloqueados`,
    `${COMMANDS.UNBAN} @usuario - Desbloquear un usuario`,
    `${COMMANDS.ADMIN} @usuario - Agregar administrador del grupo`,
    `${COMMANDS.NO_ADMIN} @usuario - Quitar administrador del grupo`,
    `${COMMANDS.PAUSE} <cantidad><m/h/d> o ${INFINITE_TOKEN} - Pausar respuestas del bot en el grupo`,
    `${COMMANDS.UNPAUSE} - Reanudar respuestas del bot en el grupo`,
  ].join("\n"),
]);

const MESSAGES = Object.freeze({
  WELCOME: `¡Hola! Soy Munin 🐦‍⬛, un bot asistente de WhatsApp creado por Capi. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,

  PONG: "pong",

  SAVE_MESSAGE_USAGE: `Uso: responde a un mensaje con ${COMMANDS.SAVE_MESSAGE} <título>`,
  SAVED_MESSAGE_CREATED: (title) => `Mensaje guardado como: ${title}`,
  SAVED_MESSAGE_UPDATED: (title) => `Mensaje guardado actualizado: ${title}`,
  VIEW_SAVED_MESSAGE_USAGE: `Uso: ${COMMANDS.VIEW_SAVED_MESSAGE} <título>`,
  SAVED_MESSAGE_REPLY: (title) => `Mensaje guardado: ${title}`,
  SAVED_MESSAGE_NOT_FOUND: (title) => `No existe un mensaje guardado con el título: ${title}`,
  NO_SAVED_MESSAGES: "No hay mensajes guardados en este grupo.",
  SAVED_MESSAGES_LIST: (messages) => `Mensajes guardados:\n${messages.map((message, index) => `${index + 1}. ${message.title}`).join("\n")}`,

  CUSTOM_COMMAND_USAGE: `Uso: ${COMMANDS.CREATE_CUSTOM_COMMAND} !<nombre> <respuesta>`,
  CUSTOM_COMMAND_CREATED: (command) => `Comando personalizado creado: ${command}`,
  CUSTOM_COMMAND_UPDATED: (command) => `Comando personalizado actualizado: ${command}`,
  CUSTOM_COMMAND_DELETED: (command) => `Comando personalizado eliminado: ${command}`,
  CUSTOM_COMMAND_BUILTIN_CONFLICT: (command) => `No puedes sobrescribir ${command} porque es un comando del bot.`,

  PENDING_USAGE: `Uso: ${COMMANDS.PENDING} [@<dd/mm>] <pendiente>, responde a un mensaje con ${COMMANDS.PENDING}, o usa ${COMMANDS.PENDING} - <índice> para eliminarlo`,
  PENDING_ADDED: (content, date) => `Pendiente agregado${date ? ` para ${date}` : ""}: ${content}`,
  NO_PENDING: "No hay pendientes guardados para este chat.",
  DAILY_PENDINGS: (groups) =>
    [
      "Pendientes de hoy:",
      groups.expired.length && `Vencidos:\n${groups.expired.join("\n")}`,
      groups.today.length && `Vencen hoy:\n${groups.today.join("\n")}`,
      groups.active.length && `Activos:\n${groups.active.join("\n")}`,
      groups.noDate.length && `Sin fecha:\n${groups.noDate.join("\n")}`,
    ]
      .filter(Boolean)
      .join("\n\n"),
  DELETE_PENDING_NOT_FOUND: "No existe un pendiente con ese índice en este chat.",
  PENDING_DELETED: (index, content) => `Pendiente ${index} eliminado: ${content}`,
  REMINDER_USAGE: `Uso: ${COMMANDS.REMINDER} <cantidad><m/h/d> [x<veces> o x] <contenido>. Responde a un mensaje para usarlo como contenido; ${COMMANDS.REMINDER} - <índice> lo elimina. Los recordatorios repetidos requieren un mínimo de 10m.`,
  RECURRING_REMINDER_ADDED: (interval, repetitions, content) => `Recordatorio repetido cada ${interval}, ${repetitions}: ${content}`,

  REMINDER_ADDED: (userTag, time, content) => `${userTag ? `${userTag} ` : ""}Te recordaré en ${time}: ${content}`,
  NO_REMINDERS: "No hay recordatorios guardados para este chat.",
  REMINDERS_LIST: (reminders) => `Recordatorios:\n${reminders.map((reminder, index) => `${index + 1}. ${reminder}`).join("\n")}`,
  DELETE_REMINDER_NOT_FOUND: "No existe un recordatorio con ese índice en este chat.",
  REMINDER_DELETED: (index, content) => `Recordatorio ${index} eliminado: ${content}`,

  COIN_RESULT: (coinFlip) => `\u{1FA99} Ha salido ${coinFlip}`,
  DICE_RESULT: (diceRoll) => `\u{1F3B2} Has sacado un ${diceRoll}`,
  EIGHT_BALL_RESULT: (response) => `\u{1F3B1} La bola 8 dice: ${response}`,

  RANDOM_RESULT: (choice) => `\u{1F3B2} He elegido: ${choice}`,
  RANDOM_USAGE: `Uso: ${COMMANDS.RANDOM} <opción1>, <opción2> ... , <opciónN>`,

  POLL_USAGE: `Uso: ${COMMANDS.POLL} <título>,<opción1>,<opción2>,...,<opciónN>`,

  // Class messages
  CURRENT_CLASS_ACTIVE: (cls) => `📚 Ahora: ${cls.name} (${cls.startTime} - ${cls.endTime}) en ${cls.classroom}`,
  CURRENT_CLASS_NEXT: (cls, day) => `📚 Siguiente: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  NO_CLASSES: "No hay clases registradas.",
  CLASSES_TODAY: (day, lines) => `📋 Clases de hoy (${day}):\n${lines.join("\n")}`,
  NO_CLASSES_TODAY: "No hay clases hoy.",
  ALL_CLASSES: (dayGroups) => `📋 Todas las clases:\n\n${dayGroups.join("\n\n")}`,
  ADD_CLASS_USAGE: `Uso: ${COMMANDS.ADD_CLASS} <nombre>, <día>, <inicio>-<fin>, <salón>\nEjemplo: ${COMMANDS.ADD_CLASS} Matemáticas, Lunes, 8:00-9:30, A-301`,
  CLASS_ADDED: (cls, day) => `✅ Clase agregada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  INVALID_DAY: "Día inválido. Usa: lunes, martes, miércoles, jueves, viernes, sábado, domingo.",
  INVALID_TIME: "Formato de horario inválido. Usa HH:mm-HH:mm (ej: 8:00-9:30).",
  EDIT_CLASS_USAGE: `Uso: ${COMMANDS.EDIT_CLASS} <nombre o índice>, <campo>=<valor>\nCampos: nombre, día, horario (HH:mm-HH:mm), salón\nEjemplo: ${COMMANDS.EDIT_CLASS} 2, horario=10:00-11:30`,
  CLASS_EDITED: (cls, day) => `✅ Clase editada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  EDIT_UNKNOWN_FIELD: (field) => `Campo desconocido: "${field}". Campos válidos: nombre, día, horario, salón.`,
  DELETE_CLASS_USAGE: `Uso: ${COMMANDS.DELETE_CLASS} <nombre o índice>`,
  CLASS_DELETED: (name) => `🗑️ Clase eliminada: ${name}`,
  CLASS_NOT_FOUND: "No se encontró la clase.",
  CLASS_AMBIGUOUS: (lines) => `Hay varias clases con ese nombre. Usa el índice de ${COMMANDS.LIST_ALL_CLASSES}:\n${lines.join("\n")}`,
  BELL_ON: "🔔 Recordatorios de 10 minutos antes de clase activados.",
  BELL_OFF: "🔕 Recordatorios de 10 minutos antes de clase desactivados.",
  CLASS_REMINDER: (cls) => `🔔 ${cls.name} empieza en 10 minutos (${cls.classroom})`,

  TIMER_USAGE: `Uso: ${COMMANDS.TIMER} <cantidad><s/m/h>`,
  TIMER_STARTED: (duration) => `⏱️ Temporizador iniciado por ${duration}.`,
  TIMER_FINISHED: "⏰ Temporizador terminado.",

  ADMIN_ONLY: "Este comando es solo para administradores.",
  BAN_USAGE: `Uso: ${COMMANDS.BAN} @usuario <cantidad><m/h/d> o ${INFINITE_TOKEN}`,
  ADMIN_USAGE: `Uso: ${COMMANDS.ADMIN} @usuario`,
  NO_ADMIN_USAGE: `Uso: ${COMMANDS.NO_ADMIN} @usuario`,
  PAUSE_USAGE: `Uso: ${COMMANDS.PAUSE} <cantidad><m/h/d> o ${INFINITE_TOKEN}`,
  USER_BANNED: (duration) => `Usuario bloqueado por ${duration}.`,
  USER_BANNED_INDEFINITELY: "Usuario bloqueado indefinidamente.",
  NO_BANS: "No hay usuarios bloqueados en este grupo.",
  BANS_LIST: (bans) => `Usuarios bloqueados:\n${bans.map(({ userId, remaining }) => `@${userId.split("@")[0]} — ${remaining}`).join("\n")}`,
  ADMIN_ADDED: "Administrador agregado para este grupo.",
  ADMIN_REMOVED: "Administrador eliminado de este grupo.",
  GLOBAL_ADMIN_PROTECTED: "El administrador global no puede ser removido.",
  BOT_PAUSED: (duration) => `Bot pausado por ${duration}.`,
  BOT_PAUSED_INDEFINITELY: "Bot pausado indefinidamente.",

  UNBAN_USAGE: `Uso: ${COMMANDS.UNBAN} @usuario`,
  USER_UNBANNED: "Usuario desbloqueado.",
  USER_NOT_BANNED: "El usuario no está bloqueado.",
  BOT_UNPAUSED: "Bot reanudado en este grupo.",
  BOT_NOT_PAUSED: "El bot no está pausado en este grupo.",
  UNKNOWN_COMMAND: (command) => `Comando no reconocido: ${command}. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,
  HELP_PAGE: (page) => HELP_PAGES[page - 1],
  HELP_PAGE_USAGE: `Uso: ${COMMANDS.HELP} <página del 1 al ${HELP_PAGE_COUNT}>`,
});

module.exports = {
  COIN_SIDES,
  COMMANDS,
  EIGHT_BALL_RESPONSES,
  INFINITE_TOKEN,
  MESSAGES,
};
