const COMMANDS = Object.freeze({
  MUNIN: "!munin",
  PING: "!ping",
  ECHO: "!echo",
  CREATE_CUSTOM_COMMAND: "!comando",
  LIST_CUSTOM_COMMANDS: "!comandos",
  SAVE_MESSAGE: "!guardar",
  VIEW_SAVED_MESSAGE: "!ver",
  LIST_SAVED_MESSAGES: "!guardados",
  DELETE_SAVED_MESSAGE: "!borrar",
  PENDING: "!p",
  REMINDER: "!r",
  COIN: "!moneda",
  DICE: "!dado",
  EIGHT_BALL: "!bola8",
  RANDOM: "!elige",
  POLL: "!encuesta",
  MULTIPLE_POLL: "!encuestam",
  TIMER: "!tiempo",
  SUMMARY: "!resumen",
  BAN: "!ban",
  CONFIG: "!config",
  UNBAN: "!unban",
  ADMIN: "!admin",
  NO_ADMIN: "!noadmin",
  PAUSE: "!pausa",
  UNPAUSE: "!despausa",
  CURRENT_CLASS: "!clase",
  LIST_CLASSES_TODAY: "!clases",
  LIST_ALL_CLASSES: "!todaslasclases",
  ADD_CLASS: "!agregarclase",
  EDIT_CLASS: "!editarclase",
  DELETE_CLASS: "!eliminarclase",
  BELL: "!campana",
  HELP: "!ayuda",
});

const COIN_SIDES = Object.freeze(["cara", "cruz"]);
const INFINITE_TOKEN = "inf";
const EIGHT_BALL_RESPONSES = Object.freeze([
  "Sí",
  "No",
  "Tal vez",
  "Definitivamente",
  "Pregunta de nuevo más tarde",
  "No cuentes con ello",
  "Es cierto",
  "No es cierto",
  "No puedo predecirlo ahora",
  "Las perspectivas son buenas",
  "Las perspectivas no son buenas",
  "Sin duda",
  "No lo creo",
  "Sí, definitivamente",
  "Mis fuentes dicen que no",
  "No puedo decirlo ahora",
  "Concéntrate y pregunta de nuevo",
  "Mi respuesta es no",
  "Mi respuesta es sí",
  "Puedes confiar en ello",
]);

const HELP_PAGE_COUNT = 5;
const HELP_SECTION_INDEX = [
  "Puedes hablar conmigo mencionando a @Munin o usar comandos con !.",
  "Usa `!ayuda <pagina>` para abrir una seccion:",
  "1. General y mensajes guardados",
  "2. Pendientes y recordatorios",
  "3. Diversion y herramientas rapidas",
  "4. Clases",
  "5. Administracion",
].join("\n");
const HELP_PAGES = Object.freeze([
  [
    `=== Ayuda 1/${HELP_PAGE_COUNT}: General ===`,
    HELP_SECTION_INDEX,
    "",
    "**Hablar con Munin**",
    "`!munin`  `!ping`  `!echo hola`",
    "",
    "**Resúmenes**",
    'Dime *"resume los últimos 20 mensajes"*.',
    "`!resumen 20`",
    "",
    "**Comandos personalizados**",
    "`!comando !saludo Hola, manada`",
    "Consulta o elimina los comandos del grupo: `!comandos`  `!comando - 1`",
    "",
    "**Mensajes guardados**",
    'Responde a un mensaje y dime *"guarda esto como reglas"*.',
    "`!guardar reglas`",
    'Dime *"muestrame reglas"*.',
    "Puedes verlo, listar los títulos o borrarlo `!ver reglas`  `!guardados`  `!borrar 1`",
    "",
    "Cambia de página con `!ayuda 2`.",
  ].join("\n"),
  [
    `=== Ayuda 2/${HELP_PAGE_COUNT}: Pendientes y recordatorios ===`,
    HELP_SECTION_INDEX,
    "",
    "**Recordatorios**",
    'Dime *"recuérdame pagarle a Juan mañana a las 17:00"*.',
    "Como comando relativo desde ahora: `!r 1d pagarle a Juan`",
    "Para repetirlo: `!r 30m x3 tomar agua`  |  Para repetirlo siempre: `!r 30m inf tomar agua`",
    'Dime *"muéstra mis recordatorios"* o *"quita el recordatorio 1 de la lista"*.',
    "Consulta o elimina recordatorios: `!r`  `!r - 1`",
    "",
    "**Pendientes**",
    'Dime *"anota comprar hielo como pendiente"*.',
    "`!p comprar hielo`",
    "Puedes añadir fecha y hora, o responder a un mensaje: `!p @25/12 10:00 comprar hielo`  `!p`",
    'Dime *"muéstra mis pendientes"* o *"quita el pendiente 1 de la lista"*.',
    "Consulta o elimina pendientes: `!p`  `!p - 1`",
  ].join("\n"),
  [
    `=== Ayuda 3/${HELP_PAGE_COUNT}: Diversion y herramientas rapidas ===`,
    HELP_SECTION_INDEX,
    "",
    "**Decidir al azar**",
    "`!elige pizza, tacos`",
    "",
    "**Juegos rápidos**",
    "Lanza una moneda, un dado o consulta la bola 8: `!moneda`  `!dado`  `!bola8`",
    "",
    "**Encuestas**",
    "`!encuesta ¿Qué cenamos?,Pizza,Tacos`",
    "Para permitir varias respuestas: `!encuestam Snacks,Papas,Palomitas,Chocolate`",
    "",
    'Dime *"Pon un temporizador de 10 minutos"*.',
    "**Temporizadores**",
    "`!tiempo 10m`",
  ].join("\n"),
  [
    `=== Ayuda 4/${HELP_PAGE_COUNT}: Clases ===`,
    HELP_SECTION_INDEX,
    "",
    'Dime *"muéstrame mis clases de hoy"*.',
    'Dime *"muéstrame mi horario"*.',
    "Consulta la clase actual o siguiente, las de hoy, o toda la semana: `!clase`  `!clases`  `!todaslasclases`",
    "",
    "**Agregar una clase**",
    'Dime *"agrega Matemáticas el lunes de 8 a 9:30 en A-301"*.',
    "`!agregarclase Matemáticas, lunes, 08:00-09:30, A-301`",
    "",
    "**Editar o eliminar**",
    "Usa el nombre o índice de la lista: `!editarclase 2, horario=10:00-11:30`  `!eliminarclase 2`",
    "",
    'Dime *"apaga/enciende la campana"*.',
    "**Campana de clases**",
    "Activa o desactiva el aviso de 10 minutos antes de cada clase: `!campana`",
  ].join("\n"),
  [
    `=== Ayuda 5/${HELP_PAGE_COUNT}: Administracion ===`,
    HELP_SECTION_INDEX,
    "",
    "**Bloqueos**",
    "Bloquea temporalmente a alguien o retíralos: `!ban @usuario 1h` `!unban @usuario`",
    `Para un bloqueo indefinido usa: \`!ban @usuario ${INFINITE_TOKEN}\``,
    "Consulta la lista de usuarios bloqueados y administradores: `!config`",
    "",
    "**Administradores**",
    "Da o quita permisos de administrador: `!admin @usuario`  `!noadmin @usuario`",
    "",
    "**Pausar Munin**",
    `Pausa respuestas en este grupo: \`!pausa 30m\`  |  Indefinidamente: \`!pausa ${INFINITE_TOKEN}\``,
    "Reanuda respuestas: `!despausa`",
  ].join("\n"),
]);
const MESSAGES = Object.freeze({
  WELCOME: `¡Hola! Soy Munin 🐦‍⬛, un bot asistente de WhatsApp creado por Capi. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,

  PONG: "pong",
  MUTATION_WITH_LIST: (confirmation, list) => `${confirmation}\n\n${list}`,
  SUMMARY_USAGE: (maxAmount) => `Uso: ${COMMANDS.SUMMARY} <cantidad entre 1 y ${maxAmount}>`,
  SUMMARY_NO_MESSAGES: "No hay mensajes anteriores para resumir en este chat.",
  SUMMARY_UNAVAILABLE: "No pude generar el resumen. Inténtalo de nuevo.",

  SAVE_MESSAGE_USAGE: `Uso: responde a un mensaje con ${COMMANDS.SAVE_MESSAGE} <título>`,
  SAVED_MESSAGE_CREATED: (title) => `Mensaje guardado como: ${title}`,
  SAVED_MESSAGE_UPDATED: (title) => `Mensaje guardado actualizado: ${title}`,
  VIEW_SAVED_MESSAGE_USAGE: `Uso: ${COMMANDS.VIEW_SAVED_MESSAGE} <título>`,
  SAVED_MESSAGE_REPLY: (title) => `Mensaje guardado: ${title}`,
  SAVED_MESSAGE_NOT_FOUND: (title) => `No existe un mensaje guardado con el título: ${title}`,
  DELETE_SAVED_MESSAGE_USAGE: `Uso: ${COMMANDS.DELETE_SAVED_MESSAGE} <índice>`,
  SAVED_MESSAGE_INDEX_NOT_FOUND: "No existe un mensaje guardado con ese índice.",
  SAVED_MESSAGE_DELETED: (title) => `Mensaje guardado eliminado: ${title}`,
  NO_SAVED_MESSAGES: "No hay mensajes guardados en este grupo.",
  SAVED_MESSAGES_LIST: (messages) =>
    `🐦‍⬛ Cosas que me pediste recordar:\n${messages.map((message, index) => `${index + 1}. ${message.title}`).join("\n")}`,

  CUSTOM_COMMAND_USAGE: `Uso: ${COMMANDS.CREATE_CUSTOM_COMMAND} !<nombre> <respuesta>`,
  CUSTOM_COMMAND_CREATED: (command, reply) => `Cuando digas ${command} diré ${reply}`,
  CUSTOM_COMMAND_UPDATED: (command) => `Comando personalizado actualizado: ${command}`,
  CUSTOM_COMMAND_DELETED: (command) => `Comando personalizado eliminado: ${command}`,
  CUSTOM_COMMAND_BUILTIN_CONFLICT: (command) => `No puedes sobrescribir ${command} porque es un comando del bot.`,
  DELETE_CUSTOM_COMMAND_USAGE: `Uso: ${COMMANDS.CREATE_CUSTOM_COMMAND} - <índice>`,
  CUSTOM_COMMAND_INDEX_NOT_FOUND: "No existe un comando personalizado con ese índice.",
  NO_CUSTOM_COMMANDS: "No hay comandos personalizados en este grupo.",
  CUSTOM_COMMANDS_LIST: (commands) => `Comandos personalizados:\n${commands.map((command, index) => `${index + 1}. ${command.command}`).join("\n")}`,

  PENDING_USAGE: `Uso: ${COMMANDS.PENDING} [@<dd/mm>] [HH:mm] <pendiente>, responde a un mensaje con ${COMMANDS.PENDING}, o usa ${COMMANDS.PENDING} - <índice> para eliminarlo`,
  PENDING_ADDED: (content, date, time) => `Pendiente agregado${date ? ` para ${date}` : ""}${time ? ` a las ${time}` : ""}: ${content}`,
  NO_PENDING: "No hay pendientes guardados para este chat.",
  DAILY_PENDINGS: (groups) =>
    [
      "🐦‍⬛ Esto es lo que se tiene pendiente:",
      groups.expired.length && `Ya se te pasaron:\n${groups.expired.join("\n")}`,
      groups.today.length && `Para hoy, no se te olviden:\n${groups.today.join("\n")}`,
      groups.active.length && `Todavía hay tiempo:\n${groups.active.join("\n")}`,
      groups.noDate.length && `Estos andan sin rumbo ni fecha:\n${groups.noDate.join("\n")}`,
    ]
      .filter(Boolean)
      .join("\n\n"),
  DELETE_PENDING_NOT_FOUND: "No existe un pendiente con ese índice en este chat.",
  PENDING_DELETED: (index, content) => `Pendiente ${index} eliminado: ${content}`,
  REMINDER_USAGE: `Uso: ${COMMANDS.REMINDER} <cantidad><m/h/d> [x<veces> o ${INFINITE_TOKEN}] <contenido>. Responde a un mensaje para usarlo como contenido; ${COMMANDS.REMINDER} - <índice> lo elimina. Los recordatorios repetidos requieren un mínimo de 10m.`,
  REMINDER_INVALID_DURATION: "No entendí el tiempo del recordatorio. Usa una cantidad positiva seguida de m, h o d; por ejemplo: 30m, 2h o 1d.",
  REMINDER_INVALID_ABSOLUTE_TIME: "No entendí la fecha u hora del recordatorio. Usa hoy o mañana y una hora HH:mm, por ejemplo: hoy a las 10:00.",
  REMINDER_TIME_ALREADY_PASSED: "Esa hora de hoy ya paso. Indica una hora futura o pide el recordatorio para mañana.",
  RECURRING_REMINDER_ADDED: (interval, repetitions, content) => `Recordatorio repetido cada ${interval}, ${repetitions}: ${content}`,

  REMINDER_ADDED: (userTag, time, content) => `${userTag ? `${userTag} ` : ""}Te recordaré en ${time}: ${content}`,
  REMINDER_CREATED: (content, dueAt) => `Recordatorio agregado para ${dueAt}: ${content}`,
  REMINDER_DUE: (content) => `🐦‍⬛ Recordar: ${content}`,
  NO_REMINDERS: "No hay recordatorios guardados para este chat.",
  REMINDERS_LIST: (reminders) =>
    `🐦‍⬛ Cosas que no debo dejarte olvidar:\n${reminders.map((reminder, index) => `${index + 1}. ${reminder}`).join("\n")}`,

  DELETE_REMINDER_NOT_FOUND: "No existe un recordatorio con ese índice en este chat.",
  REMINDER_DELETED: (index, content) => `Recordatorio ${index} eliminado: ${content}`,

  COIN_RESULT: (coinFlip) => `\u{1FA99} Ha salido ${coinFlip}`,
  DICE_RESULT: (diceRoll) => `\u{1F3B2} Has sacado un ${diceRoll}`,
  EIGHT_BALL_RESULT: (response) => `\u{1F3B1} La bola 8 dice: ${response}`,

  RANDOM_RESULT: (choice) => `\u{1F3B2} He elegido: ${choice}`,
  RANDOM_USAGE: `Uso: ${COMMANDS.RANDOM} <opción1>, <opción2> ... , <opciónN>`,

  POLL_USAGE: `Uso: ${COMMANDS.POLL} <título>,<opción1>,<opción2>,...,<opciónN>`,

  // Class messages
  CURRENT_CLASS_ACTIVE: (cls) => `📚 Ahora: ${cls.name} (${cls.startTime} - ${cls.endTime}) en ${cls.classroom}`,
  CURRENT_CLASS_NEXT: (cls, day) => `📚 Siguiente: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  NO_CLASSES: "No hay clases registradas.",
  CLASSES_TODAY: (day, lines, bellEnabled) =>
    `🐦‍⬛ Estas son las clases de hoy (${day}):\n${bellEnabled ? "🔔 Campana activada" : "🔕 Campana desactivada"}\n\n${lines.join("\n")}`,
  NO_CLASSES_TODAY: "No hay clases hoy.",
  ALL_CLASSES: (dayGroups, bellEnabled) =>
    `🐦‍⬛ Estas son todas las clases:\n${bellEnabled ? "🔔 Campana activada" : "🔕 Campana desactivada"}\n\n${dayGroups.join("\n\n")}`,
  ADD_CLASS_USAGE: `Uso: ${COMMANDS.ADD_CLASS} <nombre>, <día>, <inicio>-<fin>, <salón>\nEjemplo: ${COMMANDS.ADD_CLASS} Matemáticas, Lunes, 8:00-9:30, A-301`,
  CLASS_ADDED: (cls, day) => `✅ Clase agregada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  INVALID_DAY: "Día inválido. Usa: lunes, martes, miércoles, jueves, viernes, sábado, domingo.",
  INVALID_TIME: "Formato de horario inválido. Usa HH:mm-HH:mm (ej: 8:00-9:30).",
  EDIT_CLASS_USAGE: `Uso: ${COMMANDS.EDIT_CLASS} <nombre o índice>, <campo>=<valor>\nCampos: nombre, día, horario (HH:mm-HH:mm), salón\nEjemplo: ${COMMANDS.EDIT_CLASS} 2, horario=10:00-11:30`,
  CLASS_EDITED: (cls, day) => `✅ Clase editada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  EDIT_UNKNOWN_FIELD: (field) => `Campo desconocido: "${field}". Campos válidos: nombre, día, horario, salón.`,
  DELETE_CLASS_USAGE: `Uso: ${COMMANDS.DELETE_CLASS} <nombre o índice>`,
  CLASS_DELETED: (name) => `🗑️ Clase eliminada: ${name}`,
  CLASS_NOT_FOUND: "No se encontró la clase.",
  CLASS_AMBIGUOUS: (lines) => `Hay varias clases con ese nombre. Usa el índice de ${COMMANDS.LIST_ALL_CLASSES}:\n${lines.join("\n")}`,
  BELL_ON: "🔔 Recordatorios de 10 minutos antes de clase activados.",
  BELL_OFF: "🔕 Recordatorios de 10 minutos antes de clase desactivados.",
  CLASS_REMINDER: (cls) => `🔔 ${cls.name} empieza en 10 minutos (${cls.classroom})`,

  TIMER_USAGE: `Uso: ${COMMANDS.TIMER} <cantidad><s/m/h>`,
  TIMER_STARTED: (duration) => `🐦‍⬛ Estaré contando por ${duration}.`,
  TIMER_FINISHED: "🪶 El tiempo se ha acabado.",

  ADMIN_ONLY: "Este comando es solo para administradores.",
  BAN_USAGE: `Uso: ${COMMANDS.BAN} @usuario <cantidad><m/h/d> o ${INFINITE_TOKEN}`,
  ADMIN_USAGE: `Uso: ${COMMANDS.ADMIN} @usuario`,
  NO_ADMIN_USAGE: `Uso: ${COMMANDS.NO_ADMIN} @usuario`,
  PAUSE_USAGE: `Uso: ${COMMANDS.PAUSE} <cantidad><m/h/d> o ${INFINITE_TOKEN}`,
  USER_BANNED: (duration) => `Usuario bloqueado por ${duration}.`,
  USER_BANNED_INDEFINITELY: "Usuario bloqueado indefinidamente.",
  CONFIG_LIST: (bans, admins) =>
    [
      "*Configuración del grupo*",
      "",
      "*Usuarios bloqueados:*",
      bans.length
        ? bans.map(({ userId, remaining }) => `@${userId.split("@")[0]} — ${remaining}`).join("\n")
        : "No hay usuarios bloqueados en este grupo.",
      "",
      "*Administradores:*",
      admins.length ? admins.map((userId) => `@${userId.split("@")[0]}`).join("\n") : "No hay administradores en este grupo.",
    ].join("\n"),
  ADMIN_ADDED: "Administrador agregado para este grupo.",
  ADMIN_REMOVED: "Administrador eliminado de este grupo.",
  GLOBAL_ADMIN_PROTECTED: "El administrador global no puede ser removido.",
  BOT_PAUSED: (duration) => `Bot pausado por ${duration}.`,
  BOT_PAUSED_INDEFINITELY: "Bot pausado indefinidamente.",
  TEST_MODE_MAINTENANCE: "🐦‍⬛ *Munin está arreglándose las plumas.*\nPor ahora no podré responder. Volveré cuando todo esté en orden.",

  UNBAN_USAGE: `Uso: ${COMMANDS.UNBAN} @usuario`,
  USER_UNBANNED: "Usuario desbloqueado.",
  USER_NOT_BANNED: "El usuario no está bloqueado.",
  BOT_UNPAUSED: "Bot reanudado en este grupo.",
  BOT_NOT_PAUSED: "El bot no está pausado en este grupo.",
  SUGGEST_SIMILAR_COMMAND: (command) => `Intenta ${command} o usa !ayuda para ver los comandos disponibles`,
  UNKNOWN_COMMAND: (command) => `Comando no reconocido: ${command}. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,
  HELP_PAGE: (page) => HELP_PAGES[page - 1],
  HELP_PAGE_USAGE: `Uso: ${COMMANDS.HELP} <página del 1 al ${HELP_PAGE_COUNT}>`,
});

module.exports = {
  COIN_SIDES,
  COMMANDS,
  EIGHT_BALL_RESPONSES,
  INFINITE_TOKEN,
  MESSAGES,
};
