const COMMANDS = Object.freeze({
  MUNIN: "!munin",
  PING: "!ping",
  ECHO: "!echo",
  ADD_NOTE: "!nota",
  LIST_NOTES: "!notas",
  DELETE_NOTE: "!borrarnota",
  ADD_REMINDER: "!memo",
  LIST_REMINDERS: "!memos",
  DELETE_REMINDER: "!borrarmemo",
  COIN: "!moneda",
  DICE: "!dado",
  EIGHT_BALL: "!bola8",
  RANDOM: "!escoge",
  POLL: "!encuesta",
  MULTIPLE_POLL: "!encuestam",
  TIMER: "!tiempo",
  CURRENT_CLASS: "!clase",
  LIST_CLASSES_TODAY: "!clases",
  LIST_ALL_CLASSES: "!todaslasclases",
  ADD_CLASS: "!agregarclase",
  EDIT_CLASS: "!editarclase",
  DELETE_CLASS: "!eliminarclase",
  BELL: "!campana",
  HELP: "!ayuda",
});

const COIN_SIDES = Object.freeze(["cara", "cruz"]);
const EIGHT_BALL_RESPONSES = Object.freeze([
  "Sí",
  "No",
  "Tal vez",
  "Definitivamente",
  "Pregunta de nuevo más tarde",
  "No cuentes con ello",
  "Es cierto",
  "No es cierto",
]);

const MESSAGES = Object.freeze({
  WELCOME: `¡Hola! Soy Munin, un bot asistente de WhatsApp creado por Capi. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,

  PONG: "pong",

  ADD_NOTE_USAGE: `Uso: ${COMMANDS.ADD_NOTE} <nota> o responde a un mensaje con ${COMMANDS.ADD_NOTE}`,
  NOTE_ADDED: (content) => `Nota agregada: ${content}`,
  NO_NOTES: "No hay notas guardadas para este chat.",
  NOTES_LIST: (notes) => `Notas:\n${notes.map((note, index) => `${index + 1}. ${note}`).join("\n")}`,
  DELETE_NOTE_USAGE: `Uso: ${COMMANDS.DELETE_NOTE} <índice>`,
  DELETE_NOTE_NOT_FOUND: "No existe una nota con ese índice en este chat.",
  NOTE_DELETED: (index) => `Nota ${index} eliminada.`,
  ADD_REMINDER_USAGE: `Uso: ${COMMANDS.ADD_REMINDER} <cantidad><m/h/d> <contenido>. Ejemplo: ${COMMANDS.ADD_REMINDER} 30m barrer`,

  REMINDER_ADDED: (userTag, time, content) => `${userTag ? `${userTag} ` : ""}Te recordaré en ${time}: ${content}`,
  NO_REMINDERS: "No hay recordatorios guardados para este chat.",
  REMINDERS_LIST: (reminders) => `Recordatorios:\n${reminders.map((reminder, index) => `${index + 1}. ${reminder}`).join("\n")}`,
  DELETE_REMINDER_USAGE: `Uso: ${COMMANDS.DELETE_REMINDER} <índice>`,
  DELETE_REMINDER_NOT_FOUND: "No existe un recordatorio con ese índice en este chat.",

  REMINDER_DELETED: (index) => `Recordatorio ${index} eliminado.`,
  COIN_RESULT: (coinFlip) => `\u{1FA99} Ha salido ${coinFlip}`,
  DICE_RESULT: (diceRoll) => `\u{1F3B2} Has sacado un ${diceRoll}`,
  EIGHT_BALL_RESULT: (response) => `\u{1F3B1} La bola 8 dice: ${response}`,

  RANDOM_RESULT: (choice) => `\u{1F3B2} He elegido: ${choice}`,
  RANDOM_USAGE: `Uso: ${COMMANDS.RANDOM} <opción1>, <opción2> ... , <opciónN>`,

  POLL_USAGE: `Uso: ${COMMANDS.POLL} <título>,<opción1>,<opción2>,...,<opciónN>`,

  // Class messages
  CURRENT_CLASS_ACTIVE: (cls) => `📚 Ahora: ${cls.name} (${cls.startTime} - ${cls.endTime}) en ${cls.classroom}`,
  CURRENT_CLASS_NEXT: (cls, day) => `📚 Siguiente: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  NO_CLASSES: "No hay clases registradas.",
  CLASSES_TODAY: (day, lines) => `📋 Clases de hoy (${day}):\n${lines.join("\n")}`,
  NO_CLASSES_TODAY: "No hay clases hoy.",
  ALL_CLASSES: (dayGroups) => `📋 Todas las clases:\n\n${dayGroups.join("\n\n")}`,
  ADD_CLASS_USAGE: `Uso: ${COMMANDS.ADD_CLASS} <nombre>, <día>, <inicio>-<fin>, <salón>\nEjemplo: ${COMMANDS.ADD_CLASS} Matemáticas, Lunes, 8:00-9:30, A-301`,
  CLASS_ADDED: (cls, day) => `✅ Clase agregada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  INVALID_DAY: "Día inválido. Usa: lunes, martes, miércoles, jueves, viernes, sábado, domingo.",
  INVALID_TIME: "Formato de horario inválido. Usa HH:mm-HH:mm (ej: 8:00-9:30).",
  EDIT_CLASS_USAGE: `Uso: ${COMMANDS.EDIT_CLASS} <nombre o índice>, <campo>=<valor>\nCampos: nombre, día, horario (HH:mm-HH:mm), salón\nEjemplo: ${COMMANDS.EDIT_CLASS} 2, horario=10:00-11:30`,
  CLASS_EDITED: (cls, day) => `✅ Clase editada: ${cls.name} — ${day} ${cls.startTime} - ${cls.endTime} en ${cls.classroom}`,
  EDIT_UNKNOWN_FIELD: (field) => `Campo desconocido: "${field}". Campos válidos: nombre, día, horario, salón.`,
  DELETE_CLASS_USAGE: `Uso: ${COMMANDS.DELETE_CLASS} <nombre o índice>`,
  CLASS_DELETED: (name) => `🗑️ Clase eliminada: ${name}`,
  CLASS_NOT_FOUND: "No se encontró la clase.",
  CLASS_AMBIGUOUS: (lines) => `Hay varias clases con ese nombre. Usa el índice de ${COMMANDS.LIST_ALL_CLASSES}:\n${lines.join("\n")}`,
  BELL_ON: "🔔 Recordatorios de 10 minutos antes de clase activados.",
  BELL_OFF: "🔕 Recordatorios de 10 minutos antes de clase desactivados.",
  CLASS_REMINDER: (cls) => `🔔 ${cls.name} empieza en 10 minutos (${cls.classroom})`,

  TIMER_USAGE: `Uso: ${COMMANDS.TIMER} <cantidad><s/m/h>`,
  TIMER_STARTED: (duration) => `⏱️ Temporizador iniciado por ${duration}.`,
  TIMER_FINISHED: "⏰ Temporizador terminado.",
  UNKNOWN_COMMAND: `Comando no reconocido. Escribe ${COMMANDS.HELP} para ver los comandos disponibles.`,
  HELP: [
    "===General===",
    `${COMMANDS.MUNIN} - Saludar al bot`,
    `${COMMANDS.PING} - Probar el bot`,
    `${COMMANDS.ECHO} <texto> - Repetir texto`,
    `${COMMANDS.HELP} - Mostrar comandos`,
    "",
    "===Notas y recordatorios===",
    `${COMMANDS.ADD_NOTE} <nota> - Guardar una nota`,
    `${COMMANDS.LIST_NOTES} - Mostrar las notas del chat`,
    `${COMMANDS.DELETE_NOTE} <índice> - Eliminar una nota`,
    `${COMMANDS.ADD_REMINDER} <cantidad><m/h/d> <contenido> - Crear un recordatorio`,
    `${COMMANDS.LIST_REMINDERS} - Mostrar los recordatorios del chat`,
    `${COMMANDS.DELETE_REMINDER} <índice> - Eliminar un recordatorio`,
    "",
    "===Diversión===",
    `${COMMANDS.COIN} - Lanzar una moneda`,
    `${COMMANDS.DICE} - Lanzar un dado`,
    `${COMMANDS.EIGHT_BALL} - Preguntar a la bola 8`,
    `${COMMANDS.RANDOM} <opción1>, <opción2> ... , <opciónN> - Elegir una opción al azar`,
    `${COMMANDS.POLL} <título>,<opción1>,<opción2>,...,<opciónN> - Crear una encuesta`,
    `${COMMANDS.MULTIPLE_POLL} <título>,<opción1>,<opción2>,...,<opciónN> - Crear una encuesta de selección múltiple`,
    `${COMMANDS.TIMER} <cantidad><s/m/h> - Iniciar un temporizador`,
    "",
    "===Clases===",
    `${COMMANDS.CURRENT_CLASS} - Mostrar la clase actual o la siguiente`,
    `${COMMANDS.LIST_CLASSES_TODAY} - Mostrar las clases de hoy`,
    `${COMMANDS.LIST_ALL_CLASSES} - Mostrar todas las clases`,
    `${COMMANDS.ADD_CLASS} <nombre>, <día>, <inicio>-<fin>, <salón> - Agregar una clase`,
    `${COMMANDS.EDIT_CLASS} <nombre o índice>, <campo>=<valor> - Editar una clase`,
    `${COMMANDS.DELETE_CLASS} <nombre o índice> - Eliminar una clase`,
    `${COMMANDS.BELL} - Activar/desactivar recordatorios de 10 minutos antes de clase`,
  ].join("\n"),
});

module.exports = {
  COIN_SIDES,
  COMMANDS,
  EIGHT_BALL_RESPONSES,
  MESSAGES,
};
